services:
  api-service:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    environment:
          JWT_SECRET_KEY: U3FQ8kc39kVo2TL7Bxt6uWWSYunevOfeKt1mI710heU=
    networks:
      - backend

networks:
  backend:
    driver: bridge