services:
  api-service:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '81:8080'
    environment:
          JWT_SECRET_KEY: 6M4gWvzEfR5ORdyS/Rseor4df7Id1RSJz1WG5XKrjP4=
    networks:
      - backend

networks:
  backend:
    driver: bridge